<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="MAIN" Id="{57a921db-ef5b-4e7a-9f5a-c29fdfc2cb69}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	axis1: AXIS_REF;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>